In [1]:
import pandas as pd

In [ ]:
# import the statewide staffing data
staffing_2024 = pd.read_csv("data/ccd_state_staffing_073124.csv")

# show me the info and head of the data
staffing_2024.info()
staffing_2024.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1454 entries, 0 to 1453
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   SCHOOL_YEAR      1454 non-null   object
 1   FIPST            1454 non-null   int64
 2   STATENAME        1454 non-null   object
 3   ST               1454 non-null   object
 4   SEA_NAME         1454 non-null   object
 5   STATE_AGENCY_NO  1454 non-null   int64
 6   STAFF            1454 non-null   object
 7   STAFF_COUNT      1354 non-null   float64
 8   TOTAL_INDICATOR  1454 non-null   object
 9   DMS_FLAG         1454 non-null   object
dtypes: float64(1), int64(2), object(7)
memory usage: 113.7+ KB

,SCHOOL_YEAR,FIPST,STATENAME,ST,SEA_NAME,STATE_AGENCY_NO,STAFF,STAFF_COUNT,TOTAL_INDICATOR,DMS_FLAG
0,2023-2024,1,ALABAMA,AL,Alabama State Department of Education,1,All Other Support Staff,13170.49,Category Set A,Reported
1,2023-2024,1,ALABAMA,AL,Alabama State Department of Education,1,Elementary School Counselors,999.08,Category Set A,Reported
2,2023-2024,1,ALABAMA,AL,Alabama State Department of Education,1,Elementary Teachers,18395.46,Category Set A,Reported
3,2023-2024,1,ALABAMA,AL,Alabama State Department of Education,1,Instructional Coordinators and Supervisors to ...,58.24,Category Set A,Reported
4,2023-2024,1,ALABAMA,AL,Alabama State Department of Education,1,Kindergarten Teachers,2980.76,Category Set A,Reported

In [20]:
# import the statewide enrollment data
enrollment_2024 = pd.read_csv("data/ccd_state_membership_073124.csv")

# filter to just include education unit total in total_indicator column
enrollment_2024 = enrollment_2024[enrollment_2024["TOTAL_INDICATOR"] == "Education Unit Total"]

# filter to just include the school_year, statename, and student_count columns
enrollment_2024 = enrollment_2024[["SCHOOL_YEAR", "STATENAME", "STUDENT_COUNT"]]

# Eliminate records where STATENAME is in this list BUREAU OF INDIAN EDUCATION, AMERICAN SAMOA, GUAM, PUERTO RICO, U.S. VIRGIN ISLANDS
enrollment_2024 = enrollment_2024[~enrollment_2024["STATENAME"].isin(["BUREAU OF INDIAN EDUCATION", "NORTHERN MARIANAS", "AMERICAN SAMOA", "GUAM", "PUERTO RICO", "U.S. VIRGIN ISLANDS"])]

# show me the info and head of the data
enrollment_2024.info()
enrollment_2024.head(51)

<class 'pandas.core.frame.DataFrame'>
Index: 51 entries, 227 to 12889
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SCHOOL_YEAR    51 non-null     object
 1   STATENAME      51 non-null     object
 2   STUDENT_COUNT  51 non-null     float64
dtypes: float64(1), object(2)
memory usage: 1.6+ KB

      SCHOOL_YEAR             STATENAME  STUDENT_COUNT
227     2023-2024               ALABAMA       748650.0
470     2023-2024                ALASKA       131243.0
728     2023-2024               ARIZONA      1117630.0
1002    2023-2024              ARKANSAS       485188.0
1247    2023-2024            CALIFORNIA      5837338.0
1490    2023-2024              COLORADO       865661.0
1733    2023-2024           CONNECTICUT       512652.0
1991    2023-2024              DELAWARE       141842.0
2265    2023-2024  DISTRICT OF COLUMBIA        98800.0
2510    2023-2024               FLORIDA      2872335.0
2753    2023-2024               GEORGIA      1749701.0
3011    2023-2024                HAWAII       169308.0
3255    2023-2024                 IDAHO       316414.0
3498    2023-2024              ILLINOIS      1846264.0
3756    2023-2024               INDIANA      1032723.0
4000    2023-2024                  IOWA       508112.0
4288    2023-2024                KANSAS       483505.0
4564    2023-2024              KENTUCKY       657520.0
4824    2023-2024             LOUISIANA       708190.0
5068    2023-2024                 MAINE       172545.0
5311    2023-2024              MARYLAND       890122.0
5584    2023-2024         MASSACHUSETTS       914958.0
5844    2023-2024              MICHIGAN      1426491.0
6088    2023-2024             MINNESOTA       869967.0
6346    2023-2024           MISSISSIPPI       436523.0
6590    2023-2024              MISSOURI       891248.0
6833    2023-2024               MONTANA       149291.0
7076    2023-2024              NEBRASKA       329162.0
7349    2023-2024                NEVADA       485566.0
7609    2023-2024         NEW HAMPSHIRE       166594.0
7853    2023-2024            NEW JERSEY      1392567.0
8096    2023-2024            NEW MEXICO       311719.0
8354    2023-2024              NEW YORK      2533449.0
8628    2023-2024        NORTH CAROLINA      1544289.0
8873    2023-2024          NORTH DAKOTA       119033.0
9161    2023-2024                  OHIO      1675300.0
9407    2023-2024              OKLAHOMA       698761.0
9665    2023-2024                OREGON       547425.0
9924    2023-2024          PENNSYLVANIA      1692829.0
10168   2023-2024          RHODE ISLAND       136154.0
10411   2023-2024        SOUTH CAROLINA       793860.0
10654   2023-2024          SOUTH DAKOTA       141467.0
10897   2023-2024             TENNESSEE      1004625.0
11170   2023-2024                 TEXAS      5532518.0
11415   2023-2024                  UTAH       689883.0
11673   2023-2024               VERMONT        82625.0
11917   2023-2024              VIRGINIA      1258852.0
12160   2023-2024            WASHINGTON      1093745.0
12403   2023-2024         WEST VIRGINIA       246883.0
12646   2023-2024             WISCONSIN       814202.0
12889   2023-2024               WYOMING        91036.0

In [ ]:
# Create a filter to create a new dataframe of only School Psychologists
school_psychologists = staffing_2024[staffing_2024["STAFF"] == "School Psychologists"]

# filter to just include the school_year, statename, and student_count columns
school_psychologists = school_psychologists[["SCHOOL_YEAR", "STATENAME", "STAFF", "STAFF_COUNT"]]

# Merge with the enrollment data to get only STATENAME and STUDENT_COUNT columns
school_psychologists = pd.merge(school_psychologists, enrollment_2024[["STATENAME", "STUDENT_COUNT"]], how="inner", on=["STATENAME"])

# Show me the info and head of the data
school_psychologists.info()
school_psychologists.head(51)

<class 'pandas.core.frame.DataFrame'>
Index: 57 entries, 15 to 1444
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SCHOOL_YEAR  57 non-null     object
 1   STATENAME    57 non-null     object
 2   STAFF        57 non-null     object
 3   STAFF_COUNT  56 non-null     float64
dtypes: float64(1), object(3)
memory usage: 2.2+ KB

     SCHOOL_YEAR             STATENAME                 STAFF  STAFF_COUNT
15     2023-2024               ALABAMA  School Psychologists         7.00
40     2023-2024                ALASKA  School Psychologists        83.27
65     2023-2024               ARIZONA  School Psychologists      1009.85
90     2023-2024              ARKANSAS  School Psychologists       188.70
116    2023-2024            CALIFORNIA  School Psychologists      7509.96
141    2023-2024              COLORADO  School Psychologists       965.69
166    2023-2024           CONNECTICUT  School Psychologists      1079.25
191    2023-2024              DELAWARE  School Psychologists       174.06
216    2023-2024  DISTRICT OF COLUMBIA  School Psychologists       164.84
242    2023-2024               FLORIDA  School Psychologists      1420.01
268    2023-2024               GEORGIA  School Psychologists       867.00
294    2023-2024                HAWAII  School Psychologists        97.00
320    2023-2024                 IDAHO  School Psychologists       471.97
345    2023-2024              ILLINOIS  School Psychologists      2093.25
370    2023-2024               INDIANA  School Psychologists       606.56
395    2023-2024                  IOWA  School Psychologists       297.70
420    2023-2024                KANSAS  School Psychologists       436.98
445    2023-2024              KENTUCKY  School Psychologists       454.00
471    2023-2024             LOUISIANA  School Psychologists       247.72
497    2023-2024                 MAINE  School Psychologists       832.89
523    2023-2024              MARYLAND  School Psychologists       845.00
548    2023-2024         MASSACHUSETTS  School Psychologists      1381.94
573    2023-2024              MICHIGAN  School Psychologists      1053.16
599    2023-2024             MINNESOTA  School Psychologists       822.19
625    2023-2024           MISSISSIPPI  School Psychologists        41.14
651    2023-2024              MISSOURI  School Psychologists       483.09
676    2023-2024               MONTANA  School Psychologists       152.41
702    2023-2024              NEBRASKA  School Psychologists       368.62
727    2023-2024                NEVADA  School Psychologists       250.80
753    2023-2024         NEW HAMPSHIRE  School Psychologists       233.82
778    2023-2024            NEW JERSEY  School Psychologists      2111.27
804    2023-2024            NEW MEXICO  School Psychologists        35.17
830    2023-2024              NEW YORK  School Psychologists      4651.00
856    2023-2024        NORTH CAROLINA  School Psychologists       789.67
882    2023-2024          NORTH DAKOTA  School Psychologists        98.84
907    2023-2024                  OHIO  School Psychologists      2054.68
933    2023-2024              OKLAHOMA  School Psychologists       176.08
958    2023-2024                OREGON  School Psychologists       427.90
983    2023-2024          PENNSYLVANIA  School Psychologists      1673.36
1009   2023-2024          RHODE ISLAND  School Psychologists       225.00
1034   2023-2024        SOUTH CAROLINA  School Psychologists       611.24
1059   2023-2024          SOUTH DAKOTA  School Psychologists       102.59
1085   2023-2024             TENNESSEE  School Psychologists       547.00
1110   2023-2024                 TEXAS  School Psychologists      2466.88
1136   2023-2024                  UTAH  School Psychologists      1623.85
1162   2023-2024               VERMONT  School Psychologists        90.74
1188   2023-2024              VIRGINIA  School Psychologists      1081.91
1213   2023-2024            WASHINGTON  School Psychologists      1120.92
1238   2023-2024         WEST VIRGINIA  School Psychologists       137.87
1264   2023-2024             WISCONSIN  School Psychologists      1054.91
1290   2023-2024               WYOMING  School Psychologists        96.05

In [ ]:
# Follow that same pattern to create a new dataframe of only Guidance Counselors
# This ensures that we're getting the derived TOTAL for separately-reported broken out counselors at all levels
school_counselors = staffing_2024[staffing_2024["STAFF"] == "Guidance Counselors"]

# filter to just include the school_year, statename, and student_count columns
school_counselors = school_counselors[["SCHOOL_YEAR", "STATENAME", "STAFF", "STAFF_COUNT"]]

# Merge with the enrollment data to get only STATENAME and STUDENT_COUNT columns
school_counselors = pd.merge(school_counselors, enrollment_2024[["STATENAME", "STUDENT_COUNT"]], how="inner", on=["STATENAME"])

# Show me the info and head of the data
school_counselors.info()
school_counselors.head(100)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SCHOOL_YEAR_x  51 non-null     object
 1   STATENAME      51 non-null     object
 2   STAFF          51 non-null     object
 3   STAFF_COUNT    51 non-null     float64
 4   SCHOOL_YEAR_y  51 non-null     object
 5   STUDENT_COUNT  51 non-null     float64
dtypes: float64(2), object(4)
memory usage: 2.5+ KB

,SCHOOL_YEAR_x,STATENAME,STAFF,STAFF_COUNT,SCHOOL_YEAR_y,STUDENT_COUNT
0,2023-2024,ALABAMA,Guidance Counselors,1879.78,2023-2024,748650.0
1,2023-2024,ALASKA,Guidance Counselors,330.45,2023-2024,131243.0
2,2023-2024,ARIZONA,Guidance Counselors,1731.57,2023-2024,1117630.0
3,2023-2024,ARKANSAS,Guidance Counselors,1409.11,2023-2024,485188.0
4,2023-2024,CALIFORNIA,Guidance Counselors,13164.14,2023-2024,5837338.0
5,2023-2024,COLORADO,Guidance Counselors,3418.39,2023-2024,865661.0
6,2023-2024,CONNECTICUT,Guidance Counselors,1600.76,2023-2024,512652.0
7,2023-2024,DELAWARE,Guidance Counselors,461.80,2023-2024,141842.0
8,2023-2024,DISTRICT OF COLUMBIA,Guidance Counselors,306.07,2023-2024,98800.0
9,2023-2024,FLORIDA,Guidance Counselors,6648.74,2023-2024,2872335.0
10,2023-2024,GEORGIA,Guidance Counselors,4633.60,2023-2024,1749701.0
11,2023-2024,HAWAII,Guidance Counselors,681.25,2023-2024,169308.0
12,2023-2024,IDAHO,Guidance Counselors,809.19,2023-2024,316414.0
13,2023-2024,ILLINOIS,Guidance Counselors,3742.05,2023-2024,1846264.0
14,2023-2024,INDIANA,Guidance Counselors,2080.00,2023-2024,1032723.0
15,2023-2024,IOWA,Guidance Counselors,1460.36,2023-2024,508112.0
16,2023-2024,KANSAS,Guidance Counselors,1299.31,2023-2024,483505.0
17,2023-2024,KENTUCKY,Guidance Counselors,2002.00,2023-2024,657520.0
18,2023-2024,LOUISIANA,Guidance Counselors,1596.05,2023-2024,708190.0
19,2023-2024,MAINE,Guidance Counselors,587.50,2023-2024,172545.0
20,2023-2024,MARYLAND,Guidance Counselors,2869.45,2023-2024,890122.0
21,2023-2024,MASSACHUSETTS,Guidance Counselors,2695.69,2023-2024,914958.0
22,2023-2024,MICHIGAN,Guidance Counselors,2487.57,2023-2024,1426491.0
23,2023-2024,MINNESOTA,Guidance Counselors,1609.14,2023-2024,869967.0
24,2023-2024,MISSISSIPPI,Guidance Counselors,1168.37,2023-2024,436523.0
25,2023-2024,MISSOURI,Guidance Counselors,3010.93,2023-2024,891248.0
26,2023-2024,MONTANA,Guidance Counselors,516.24,2023-2024,149291.0
27,2023-2024,NEBRASKA,Guidance Counselors,991.93,2023-2024,329162.0
28,2023-2024,NEVADA,Guidance Counselors,1055.35,2023-2024,485566.0
29,2023-2024,NEW HAMPSHIRE,Guidance Counselors,872.60,2023-2024,166594.0
30,2023-2024,NEW JERSEY,Guidance Counselors,4666.17,2023-2024,1392567.0
31,2023-2024,NEW MEXICO,Guidance Counselors,708.86,2023-2024,311719.0
32,2023-2024,NEW YORK,Guidance Counselors,8068.24,2023-2024,2533449.0
33,2023-2024,NORTH CAROLINA,Guidance Counselors,4543.36,2023-2024,1544289.0
34,2023-2024,NORTH DAKOTA,Guidance Counselors,412.34,2023-2024,119033.0
35,2023-2024,OHIO,Guidance Counselors,4372.75,2023-2024,1675300.0
36,2023-2024,OKLAHOMA,Guidance Counselors,1935.42,2023-2024,698761.0
37,2023-2024,OREGON,Guidance Counselors,1658.32,2023-2024,547425.0
38,2023-2024,PENNSYLVANIA,Guidance Counselors,5302.44,2023-2024,1692829.0
39,2023-2024,RHODE ISLAND,Guidance Counselors,377.00,2023-2024,136154.0
40,2023-2024,SOUTH CAROLINA,Guidance Counselors,2531.45,2023-2024,793860.0
41,2023-2024,SOUTH DAKOTA,Guidance Counselors,425.80,2023-2024,141467.0
42,2023-2024,TENNESSEE,Guidance Counselors,2339.81,2023-2024,1004625.0
43,2023-2024,TEXAS,Guidance Counselors,14130.89,2023-2024,5532518.0
44,2023-2024,UTAH,Guidance Counselors,1417.13,2023-2024,689883.0
45,2023-2024,VERMONT,Guidance Counselors,481.33,2023-2024,82625.0
46,2023-2024,VIRGINIA,Guidance Counselors,4372.66,2023-2024,1258852.0
47,2023-2024,WASHINGTON,Guidance Counselors,3012.66,2023-2024,1093745.0
48,2023-2024,WEST VIRGINIA,Guidance Counselors,800.07,2023-2024,246883.0
49,2023-2024,WISCONSIN,Guidance Counselors,2248.27,2023-2024,814202.0
50,2023-2024,WYOMING,Guidance Counselors,305.85,2023-2024,91036.0