In [34]:
import pandas as pd

In [ ]:
# import the statewide staffing data
staffing_2019 = pd.read_csv("data/ccd_state_staffing_091019.csv")

# show me the info and head of the data
staffing_2019.info()
staffing_2019.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1454 entries, 0 to 1453
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   SCHOOL_YEAR      1454 non-null   object
 1   FIPST            1454 non-null   int64
 2   STATENAME        1454 non-null   object
 3   ST               1454 non-null   object
 4   SEA_NAME         1454 non-null   object
 5   STATE_AGENCY_NO  1454 non-null   int64
 6   STAFF            1454 non-null   object
 7   STAFF_COUNT      1354 non-null   float64
 8   TOTAL_INDICATOR  1454 non-null   object
 9   DMS_FLAG         1454 non-null   object
dtypes: float64(1), int64(2), object(7)
memory usage: 113.7+ KB

,SCHOOL_YEAR,FIPST,STATENAME,ST,SEA_NAME,STATE_AGENCY_NO,STAFF,STAFF_COUNT,TOTAL_INDICATOR,DMS_FLAG
0,2023-2024,1,ALABAMA,AL,Alabama State Department of Education,1,All Other Support Staff,13170.49,Category Set A,Reported
1,2023-2024,1,ALABAMA,AL,Alabama State Department of Education,1,Elementary School Counselors,999.08,Category Set A,Reported
2,2023-2024,1,ALABAMA,AL,Alabama State Department of Education,1,Elementary Teachers,18395.46,Category Set A,Reported
3,2023-2024,1,ALABAMA,AL,Alabama State Department of Education,1,Instructional Coordinators and Supervisors to ...,58.24,Category Set A,Reported
4,2023-2024,1,ALABAMA,AL,Alabama State Department of Education,1,Kindergarten Teachers,2980.76,Category Set A,Reported

In [ ]:
# import the statewide enrollment data
enrollment_2019 = pd.read_csv("data/ccd_state_membership_091019.csv")

# filter to just include education unit total in total_indicator column
enrollment_2019 = enrollment_2019[enrollment_2019["TOTAL_INDICATOR"] == "Education Unit Total"]

# filter to just include the school_year, statename, and student_count columns
enrollment_2019 = enrollment_2019[["SCHOOL_YEAR", "STATENAME", "STUDENT_COUNT"]]

# Eliminate records where STATENAME is in this list BUREAU OF INDIAN EDUCATION, AMERICAN SAMOA, GUAM, PUERTO RICO, U.S. VIRGIN ISLANDS
enrollment_2019 = enrollment_2019[~enrollment_2019["STATENAME"].isin(["BUREAU OF INDIAN EDUCATION", "NORTHERN MARIANAS", "AMERICAN SAMOA", "GUAM", "PUERTO RICO", "U.S. VIRGIN ISLANDS"])]

# show me the info and head of the data
enrollment_2019.info()
enrollment_2019.head(51)

<class 'pandas.core.frame.DataFrame'>
Index: 51 entries, 227 to 12889
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SCHOOL_YEAR    51 non-null     object
 1   STATENAME      51 non-null     object
 2   STUDENT_COUNT  51 non-null     float64
dtypes: float64(1), object(2)
memory usage: 1.6+ KB

      SCHOOL_YEAR             STATENAME  STUDENT_COUNT
227     2023-2024               ALABAMA       748650.0
470     2023-2024                ALASKA       131243.0
728     2023-2024               ARIZONA      1117630.0
1002    2023-2024              ARKANSAS       485188.0
1247    2023-2024            CALIFORNIA      5837338.0
1490    2023-2024              COLORADO       865661.0
1733    2023-2024           CONNECTICUT       512652.0
1991    2023-2024              DELAWARE       141842.0
2265    2023-2024  DISTRICT OF COLUMBIA        98800.0
2510    2023-2024               FLORIDA      2872335.0
2753    2023-2024               GEORGIA      1749701.0
3011    2023-2024                HAWAII       169308.0
3255    2023-2024                 IDAHO       316414.0
3498    2023-2024              ILLINOIS      1846264.0
3756    2023-2024               INDIANA      1032723.0
4000    2023-2024                  IOWA       508112.0
4288    2023-2024                KANSAS       483505.0
4564    2023-2024              KENTUCKY       657520.0
4824    2023-2024             LOUISIANA       708190.0
5068    2023-2024                 MAINE       172545.0
5311    2023-2024              MARYLAND       890122.0
5584    2023-2024         MASSACHUSETTS       914958.0
5844    2023-2024              MICHIGAN      1426491.0
6088    2023-2024             MINNESOTA       869967.0
6346    2023-2024           MISSISSIPPI       436523.0
6590    2023-2024              MISSOURI       891248.0
6833    2023-2024               MONTANA       149291.0
7076    2023-2024              NEBRASKA       329162.0
7349    2023-2024                NEVADA       485566.0
7609    2023-2024         NEW HAMPSHIRE       166594.0
7853    2023-2024            NEW JERSEY      1392567.0
8096    2023-2024            NEW MEXICO       311719.0
8354    2023-2024              NEW YORK      2533449.0
8628    2023-2024        NORTH CAROLINA      1544289.0
8873    2023-2024          NORTH DAKOTA       119033.0
9161    2023-2024                  OHIO      1675300.0
9407    2023-2024              OKLAHOMA       698761.0
9665    2023-2024                OREGON       547425.0
9924    2023-2024          PENNSYLVANIA      1692829.0
10168   2023-2024          RHODE ISLAND       136154.0
10411   2023-2024        SOUTH CAROLINA       793860.0
10654   2023-2024          SOUTH DAKOTA       141467.0
10897   2023-2024             TENNESSEE      1004625.0
11170   2023-2024                 TEXAS      5532518.0
11415   2023-2024                  UTAH       689883.0
11673   2023-2024               VERMONT        82625.0
11917   2023-2024              VIRGINIA      1258852.0
12160   2023-2024            WASHINGTON      1093745.0
12403   2023-2024         WEST VIRGINIA       246883.0
12646   2023-2024             WISCONSIN       814202.0
12889   2023-2024               WYOMING        91036.0

In [ ]:
# Create a filter to create a new dataframe of only School Psychologists
school_psychologists_2019 = staffing_2019[staffing_2019["STAFF"] == "School Psychologists"]

# filter to just include the school_year, statename, and student_count columns
school_psychologists_2019 = school_psychologists_2019[["SCHOOL_YEAR", "STATENAME", "STAFF", "STAFF_COUNT"]]

# Merge with the enrollment data to get only STATENAME and STUDENT_COUNT columns
school_psychologists_2019 = pd.merge(school_psychologists_2019, enrollment_2019[["STATENAME", "STUDENT_COUNT"]], how="inner", on=["STATENAME"])

# Calculate a ratio of students to staff as a new column and round to one digit after decimal
school_psychologists_2019["STUDENT_TO_STAFF_RATIO"] = (school_psychologists_2019["STUDENT_COUNT"] / school_psychologists_2019["STAFF_COUNT"]).round(1)

# Show me the info and head of the data
school_psychologists_2019.info()
school_psychologists_2019.head(51)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   SCHOOL_YEAR             51 non-null     object
 1   STATENAME               51 non-null     object
 2   STAFF                   51 non-null     object
 3   STAFF_COUNT             51 non-null     float64
 4   STUDENT_COUNT           51 non-null     float64
 5   STUDENT_TO_STAFF_RATIO  51 non-null     float64
dtypes: float64(3), object(3)
memory usage: 2.5+ KB

,SCHOOL_YEAR,STATENAME,STAFF,STAFF_COUNT,STUDENT_COUNT,STUDENT_TO_STAFF_RATIO
0,2023-2024,ALABAMA,School Psychologists,7.00,748650.0,106950.0
1,2023-2024,ALASKA,School Psychologists,83.27,131243.0,1576.1
2,2023-2024,ARIZONA,School Psychologists,1009.85,1117630.0,1106.7
3,2023-2024,ARKANSAS,School Psychologists,188.70,485188.0,2571.2
4,2023-2024,CALIFORNIA,School Psychologists,7509.96,5837338.0,777.3
5,2023-2024,COLORADO,School Psychologists,965.69,865661.0,896.4
6,2023-2024,CONNECTICUT,School Psychologists,1079.25,512652.0,475.0
7,2023-2024,DELAWARE,School Psychologists,174.06,141842.0,814.9
8,2023-2024,DISTRICT OF COLUMBIA,School Psychologists,164.84,98800.0,599.4
9,2023-2024,FLORIDA,School Psychologists,1420.01,2872335.0,2022.8
10,2023-2024,GEORGIA,School Psychologists,867.00,1749701.0,2018.1
11,2023-2024,HAWAII,School Psychologists,97.00,169308.0,1745.4
12,2023-2024,IDAHO,School Psychologists,471.97,316414.0,670.4
13,2023-2024,ILLINOIS,School Psychologists,2093.25,1846264.0,882.0
14,2023-2024,INDIANA,School Psychologists,606.56,1032723.0,1702.6
15,2023-2024,IOWA,School Psychologists,297.70,508112.0,1706.8
16,2023-2024,KANSAS,School Psychologists,436.98,483505.0,1106.5
17,2023-2024,KENTUCKY,School Psychologists,454.00,657520.0,1448.3
18,2023-2024,LOUISIANA,School Psychologists,247.72,708190.0,2858.8
19,2023-2024,MAINE,School Psychologists,832.89,172545.0,207.2
20,2023-2024,MARYLAND,School Psychologists,845.00,890122.0,1053.4
21,2023-2024,MASSACHUSETTS,School Psychologists,1381.94,914958.0,662.1
22,2023-2024,MICHIGAN,School Psychologists,1053.16,1426491.0,1354.5
23,2023-2024,MINNESOTA,School Psychologists,822.19,869967.0,1058.1
24,2023-2024,MISSISSIPPI,School Psychologists,41.14,436523.0,10610.7
25,2023-2024,MISSOURI,School Psychologists,483.09,891248.0,1844.9
26,2023-2024,MONTANA,School Psychologists,152.41,149291.0,979.5
27,2023-2024,NEBRASKA,School Psychologists,368.62,329162.0,893.0
28,2023-2024,NEVADA,School Psychologists,250.80,485566.0,1936.1
29,2023-2024,NEW HAMPSHIRE,School Psychologists,233.82,166594.0,712.5
30,2023-2024,NEW JERSEY,School Psychologists,2111.27,1392567.0,659.6
31,2023-2024,NEW MEXICO,School Psychologists,35.17,311719.0,8863.2
32,2023-2024,NEW YORK,School Psychologists,4651.00,2533449.0,544.7
33,2023-2024,NORTH CAROLINA,School Psychologists,789.67,1544289.0,1955.6
34,2023-2024,NORTH DAKOTA,School Psychologists,98.84,119033.0,1204.3
35,2023-2024,OHIO,School Psychologists,2054.68,1675300.0,815.4
36,2023-2024,OKLAHOMA,School Psychologists,176.08,698761.0,3968.4
37,2023-2024,OREGON,School Psychologists,427.90,547425.0,1279.3
38,2023-2024,PENNSYLVANIA,School Psychologists,1673.36,1692829.0,1011.6
39,2023-2024,RHODE ISLAND,School Psychologists,225.00,136154.0,605.1
40,2023-2024,SOUTH CAROLINA,School Psychologists,611.24,793860.0,1298.8
41,2023-2024,SOUTH DAKOTA,School Psychologists,102.59,141467.0,1379.0
42,2023-2024,TENNESSEE,School Psychologists,547.00,1004625.0,1836.6
43,2023-2024,TEXAS,School Psychologists,2466.88,5532518.0,2242.7
44,2023-2024,UTAH,School Psychologists,1623.85,689883.0,424.8
45,2023-2024,VERMONT,School Psychologists,90.74,82625.0,910.6
46,2023-2024,VIRGINIA,School Psychologists,1081.91,1258852.0,1163.5
47,2023-2024,WASHINGTON,School Psychologists,1120.92,1093745.0,975.8
48,2023-2024,WEST VIRGINIA,School Psychologists,137.87,246883.0,1790.7
49,2023-2024,WISCONSIN,School Psychologists,1054.91,814202.0,771.8
50,2023-2024,WYOMING,School Psychologists,96.05,91036.0,947.8

In [ ]:
# Follow that same pattern to create a new dataframe of only Guidance Counselors
# This ensures that we're getting the derived TOTAL for separately-reported broken out counselors at all levels
school_counselors_2019 = staffing_2019[staffing_2019["STAFF"] == "Guidance Counselors"]

# filter to just include the school_year, statename, and student_count columns
school_counselors_2019 = school_counselors_2019[["SCHOOL_YEAR", "STATENAME", "STAFF", "STAFF_COUNT"]]

# Merge with the enrollment data to get only STATENAME and STUDENT_COUNT columns
school_counselors_2019 = pd.merge(school_counselors_2019, enrollment_2019[["STATENAME", "STUDENT_COUNT"]], how="inner", on=["STATENAME"])

# Calculate a ratio of students to staff as a new column and round to one digit after decimal
school_counselors_2019["STUDENT_TO_STAFF_RATIO"] = (school_counselors_2019["STUDENT_COUNT"] / school_counselors_2019["STAFF_COUNT"]).round(1)

# Show me the info and head of the data
school_counselors_2019.info()
school_counselors_2019.head(100)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   SCHOOL_YEAR             51 non-null     object
 1   STATENAME               51 non-null     object
 2   STAFF                   51 non-null     object
 3   STAFF_COUNT             51 non-null     float64
 4   STUDENT_COUNT           51 non-null     float64
 5   STUDENT_TO_STAFF_RATIO  51 non-null     float64
dtypes: float64(3), object(3)
memory usage: 2.5+ KB

,SCHOOL_YEAR,STATENAME,STAFF,STAFF_COUNT,STUDENT_COUNT,STUDENT_TO_STAFF_RATIO
0,2023-2024,ALABAMA,Guidance Counselors,1879.78,748650.0,398.3
1,2023-2024,ALASKA,Guidance Counselors,330.45,131243.0,397.2
2,2023-2024,ARIZONA,Guidance Counselors,1731.57,1117630.0,645.4
3,2023-2024,ARKANSAS,Guidance Counselors,1409.11,485188.0,344.3
4,2023-2024,CALIFORNIA,Guidance Counselors,13164.14,5837338.0,443.4
5,2023-2024,COLORADO,Guidance Counselors,3418.39,865661.0,253.2
6,2023-2024,CONNECTICUT,Guidance Counselors,1600.76,512652.0,320.3
7,2023-2024,DELAWARE,Guidance Counselors,461.80,141842.0,307.2
8,2023-2024,DISTRICT OF COLUMBIA,Guidance Counselors,306.07,98800.0,322.8
9,2023-2024,FLORIDA,Guidance Counselors,6648.74,2872335.0,432.0
10,2023-2024,GEORGIA,Guidance Counselors,4633.60,1749701.0,377.6
11,2023-2024,HAWAII,Guidance Counselors,681.25,169308.0,248.5
12,2023-2024,IDAHO,Guidance Counselors,809.19,316414.0,391.0
13,2023-2024,ILLINOIS,Guidance Counselors,3742.05,1846264.0,493.4
14,2023-2024,INDIANA,Guidance Counselors,2080.00,1032723.0,496.5
15,2023-2024,IOWA,Guidance Counselors,1460.36,508112.0,347.9
16,2023-2024,KANSAS,Guidance Counselors,1299.31,483505.0,372.1
17,2023-2024,KENTUCKY,Guidance Counselors,2002.00,657520.0,328.4
18,2023-2024,LOUISIANA,Guidance Counselors,1596.05,708190.0,443.7
19,2023-2024,MAINE,Guidance Counselors,587.50,172545.0,293.7
20,2023-2024,MARYLAND,Guidance Counselors,2869.45,890122.0,310.2
21,2023-2024,MASSACHUSETTS,Guidance Counselors,2695.69,914958.0,339.4
22,2023-2024,MICHIGAN,Guidance Counselors,2487.57,1426491.0,573.4
23,2023-2024,MINNESOTA,Guidance Counselors,1609.14,869967.0,540.6
24,2023-2024,MISSISSIPPI,Guidance Counselors,1168.37,436523.0,373.6
25,2023-2024,MISSOURI,Guidance Counselors,3010.93,891248.0,296.0
26,2023-2024,MONTANA,Guidance Counselors,516.24,149291.0,289.2
27,2023-2024,NEBRASKA,Guidance Counselors,991.93,329162.0,331.8
28,2023-2024,NEVADA,Guidance Counselors,1055.35,485566.0,460.1
29,2023-2024,NEW HAMPSHIRE,Guidance Counselors,872.60,166594.0,190.9
30,2023-2024,NEW JERSEY,Guidance Counselors,4666.17,1392567.0,298.4
31,2023-2024,NEW MEXICO,Guidance Counselors,708.86,311719.0,439.7
32,2023-2024,NEW YORK,Guidance Counselors,8068.24,2533449.0,314.0
33,2023-2024,NORTH CAROLINA,Guidance Counselors,4543.36,1544289.0,339.9
34,2023-2024,NORTH DAKOTA,Guidance Counselors,412.34,119033.0,288.7
35,2023-2024,OHIO,Guidance Counselors,4372.75,1675300.0,383.1
36,2023-2024,OKLAHOMA,Guidance Counselors,1935.42,698761.0,361.0
37,2023-2024,OREGON,Guidance Counselors,1658.32,547425.0,330.1
38,2023-2024,PENNSYLVANIA,Guidance Counselors,5302.44,1692829.0,319.3
39,2023-2024,RHODE ISLAND,Guidance Counselors,377.00,136154.0,361.2
40,2023-2024,SOUTH CAROLINA,Guidance Counselors,2531.45,793860.0,313.6
41,2023-2024,SOUTH DAKOTA,Guidance Counselors,425.80,141467.0,332.2
42,2023-2024,TENNESSEE,Guidance Counselors,2339.81,1004625.0,429.4
43,2023-2024,TEXAS,Guidance Counselors,14130.89,5532518.0,391.5
44,2023-2024,UTAH,Guidance Counselors,1417.13,689883.0,486.8
45,2023-2024,VERMONT,Guidance Counselors,481.33,82625.0,171.7
46,2023-2024,VIRGINIA,Guidance Counselors,4372.66,1258852.0,287.9
47,2023-2024,WASHINGTON,Guidance Counselors,3012.66,1093745.0,363.0
48,2023-2024,WEST VIRGINIA,Guidance Counselors,800.07,246883.0,308.6
49,2023-2024,WISCONSIN,Guidance Counselors,2248.27,814202.0,362.1
50,2023-2024,WYOMING,Guidance Counselors,305.85,91036.0,297.6

In [ ]:
# Export csv files for both school psychologists and school counselors
school_psychologists_2019_2019.to_csv("output/school_psychologists_2019_2019.csv", index=False)
school_counselors_2019.to_csv("output/school_counselors_2019_2019.csv", index=False)